export default function fetchDataHelper({ objectType }) {

    console.log('objectType: ' + objectType);

            switch (objectType) {
            case 'amount':
                return amountData;
                break;
            case 'grInfo':
                return grInfoData;
                break;
            case 'price':
                return priceData;
                break;
            case 'discount':
                return discountData;
                break;
            case 'value':
                return valueData;
                break;
            case 'stringValue':
                return stringData;    
        }

}

const amountData = [
    {
        Id: '1a',
        col1: '2001',
        col2: '02',
        col3: '0001',
        col4: true,
        col5: false,
        col6: false,
        col7: false,
        col8: false,
        col9: false,
        col10: false,
        col11: 'Consumo gas'
    },
    {
        Id: '2a',
        col1: '3001',
        col2: '03',
        col3: '0001',
        col4: true,
        col5: false,
        col6: false,
        col7: false,
        col8: false,
        col9: false,
        col10: false,
        col11: 'Consumo acqua'
    },
    {
        Id: '3a',
        col1: '6001',
        col2: '06',
        col3: '0001',
        col4: false,
        col5: false,
        col6: true,
        col7: false,
        col8: false,
        col9: false,
        col10: false,
        col11: 'Smaltimento rifiuti'
    },
    {
        Id: '4a',
        col1: 'ACALCMAN',
        col2: '11',
        col3: 'H001',
        col4: false,
        col5: false,
        col6: true,
        col7: false,
        col8: false,
        col9: false,
        col10: false,
        col11: 'Calcolo manuale'
    },
    {
        Id: '5a',
        col1: 'ACAMOUNT',
        col2: '11',
        col3: 'H001',
        col4: false,
        col5: false,
        col6: true,
        col7: false,
        col8: false,
        col9: false,
        col10: false,
        col11: 'Tipo Tariffa Amount-appoggio'
    },
    {
        Id: '6a',
        col1: 'ARCNDEFA',
        col2: '11',
        col3: 'H001',
        col4: false,
        col5: false,
        col6: true,
        col7: false,
        col8: false,
        col9: false,
        col10: false,
        col11: 'Gestione consumi DEFALCO'
    },
    {
        Id: '7a',
        col1: 'ATBNSUTA',
        col2: '11',
        col3: 'H001',
        col4: false,
        col5: false,
        col6: true,
        col7: false,
        col8: false,
        col9: false,
        col10: false,
        col11: 'Bonus Sociale Una tantum'
    },
    {
        Id: '8a',
        col1: 'ATBONSOC',
        col2: '11',
        col3: 'H001',
        col4: false,
        col5: false,
        col6: true,
        col7: false,
        col8: false,
        col9: false,
        col10: false,
        col11: 'Bonus Sociale ex Del 897 2017'
    },
    {
        Id: '9a',
        col1: 'ATCNBCID',
        col2: '11',
        col3: 'H001',
        col4: false,
        col5: false,
        col6: true,
        col7: false,
        col8: false,
        col9: false,
        col10: false,
        col11: 'Canone/Sconto Bocche Idrante'
    },
    {
        Id: '10a',
        col1: 'ATCNSFRF',
        col2: '11',
        col3: 'H001',
        col4: false,
        col5: false,
        col6: true,
        col7: false,
        col8: false,
        col9: false,
        col10: false,
        col11: 'Tariffa det.consumo a forfait'
    },
    {
        Id: '11a',
        col1: 'ATCNSSE1',
        col2: '11',
        col3: 'H001',
        col4: true,
        col5: false,
        col6: false,
        col7: false,
        col8: false,
        col9: false,
        col10: false,
        col11: 'Tariffa det.cons. Stag. Est. 1'
    },
    {
        Id: '12a',
        col1: 'ATCNSSE2',
        col2: '11',
        col3: 'H001',
        col4: true,
        col5: false,
        col6: false,
        col7: false,
        col8: false,
        col9: false,
        col10: false,
        col11: 'Tariffa det.cons. Stag. Est. 2'
    },
    {
        Id: '13a',
        col1: 'ATCNSSI1',
        col2: '11',
        col3: 'H001',
        col4: true,
        col5: false,
        col6: false,
        col7: false,
        col8: false,
        col9: false,
        col10: false,
        col11: 'Tariffa det.cons. Stag. Inv 1'
    },
    {
        Id: '14a',
        col1: 'ATCNSSI2',
        col2: '11',
        col3: 'H001',
        col4: true,
        col5: false,
        col6: false,
        col7: false,
        col8: false,
        col9: false,
        col10: false,
        col11: 'Tariffa det.cons. Stag. Inv 2'
    },
    {
        Id: '15a',
        col1: 'ATCNSUTC',
        col2: '11',
        col3: 'H001',
        col4: true,
        col5: false,
        col6: false,
        col7: false,
        col8: false,
        col9: false,
        col10: false,
        col11: 'Tariffa det.cons. Ut. Civili'
    },
    {
        Id: '16a',
        col1: 'ATCNSUTI',
        col2: '11',
        col3: 'H001',
        col4: true,
        col5: false,
        col6: false,
        col7: false,
        col8: false,
        col9: false,
        col10: false,
        col11: 'Tariffa det.cons. Ut. Industr.'
    },
    {
        Id: '17a',
        col1: 'ATCNSUTP',
        col2: '11',
        col3: 'H001',
        col4: true,
        col5: false,
        col6: false,
        col7: false,
        col8: false,
        col9: false,
        col10: false,
        col11: 'Tariffa det.cons. Ut. Prod.'
    },
    {
        Id: '18a',
        col1: 'ATDELETE',
        col2: '11',
        col3: 'H001',
        col4: false,
        col5: false,
        col6: true,
        col7: false,
        col8: false,
        col9: false,
        col10: false,
        col: 'Cancellazione righe importo 0'
    },
    {
        Id: '19a',
        col1: 'ATDIRATT',
        col2: '11',
        col3: 'H001',
        col4: false,
        col5: false,
        col6: true,
        col7: false,
        col8: false,
        col9: false,
        col10: false,
        col: 'Tariffa Diritti di attivazione'
    },
    {
        Id: '20a',
        col1: 'ATDPC',
        col2: '11',
        col3: 'H001',
        col4: false,
        col5: false,
        col6: true,
        col7: false,
        col8: false,
        col9: false,
        col10: false,
        col11: 'Acconto/Conguaglio'
    }
];

const grInfoData = [
    {
        Id: '1f',
		col1: 'BO001',
		col2: 'AF_GG',  
		col3: '',
		col4: '31.12.9999',
		col5: '01.01.1900',
		col6: '0',
		col7: '0',
		col8: '0',
		col9: '',
		col10: '',
		col11: '',
		col12: '3',
		col13: '0',
		col14: ''
	},
    {
        Id: '1f',
		col1: 'BO002',
		col2: 'AF_GG',  
		col3: '',
		col4: '31.12.9999',
		col5: '01.01.1900',
		col6: '0',
		col7: '0',
		col8: '0',
		col9: '',
		col10: '',
		col11: '',
		col12: '3',
		col13: '0',
		col14: ''
    },
    {
        Id: '1f',
		col1: 'BO003',
		col2: 'AF_GG',  
		col3: '',
		col4: '31.12.9999',
		col5: '01.01.1900',
		col6: '0',
		col7: '0',
		col8: '0',
		col9: '',
		col10: '',
		col11: '',
		col12: '3',
		col13: '0',
		col14: ''
    }
];

const priceData = [

    {
        Id: '1d',
        col1: '3008791479|',
        col2: '1',
        col3: '11',
        col4: 'M3',
        col5: 'H001',
        col6: '365',
        col7: '2',
        col8: '',
        col9: '',
        col10: 'H001',
        col11: '25.09.2018',
        col12: 'XFCOLLINA',
        col13: '',
        col14: '',
        col15: '',
        col16: ''
    },
    {
        Id: '1d',
        col1: 'A0191298TA',
        col2: '1',
        col3: '11',
        col4: 'M3',
        col5: 'H001',
        col6: '365',
        col7: '2',
        col8: '',
        col9: '',
        col10: 'H001',
        col11: '25.09.2018',
        col12: 'XFCOLLINA',
        col13: '',
        col14: '',
        col15: '',
        col16: ''
    },
    {
        Id: '1d',
        col1: 'A0213065TA',
        col2: '1',
        col3: '11',
        col4: 'M3',
        col5: 'H001',
        col6: '365',
        col7: '2',
        col8: '',
        col9: '',
        col10: 'H001',
        col11: '25.09.2018',
        col12: 'XFCOLLINA',
        col13: '',
        col14: '',
        col15: '',
        col16: ''
    },
    {
        Id: '1d',
        col1: 'A0437898TA',
        col2: '1',
        col3: '11',
        col4: 'M3',
        col5: 'H001',
        col6: '365',
        col7: '2',
        col8: '',
        col9: '',
        col10: 'H001',
        col11: '25.09.2018',
        col12: 'XFCOLLINA',
        col13: '',
        col14: '',
        col15: '',
        col16: ''
    },
    {
        Id: '1d',
        col1: 'A1094891TA',
        col2: '1',
        col3: '11',
        col4: 'M3',
        col5: 'H001',
        col6: '365',
        col7: '2',
        col8: '',
        col9: '',
        col10: 'H001',
        col11: '25.09.2018',
        col12: 'XFCOLLINA',
        col13: '',
        col14: '',
        col15: '',
        col16: ''
    },
    {
        Id: '1d',
        col1: 'A4837916TA',
        col2: '1',
        col3: '11',
        col4: 'M3',
        col5: 'H001',
        col6: '365',
        col7: '2',
        col8: '',
        col9: '',
        col10: 'H001',
        col11: '25.09.2018',
        col12: 'XFCOLLINA',
        col13: '',
        col14: '',
        col15: '',
        col16: ''
    },
    {
        Id: '1d',
        col1: 'A4874327TA',
        col2: '1',
        col3: '11',
        col4: 'M3',
        col5: 'H001',
        col6: '365',
        col7: '2',
        col8: '',
        col9: '',
        col10: 'H001',
        col11: '25.09.2018',
        col12: 'XFCOLLINA',
        col13: '',
        col14: '',
        col15: '',
        col16: ''
    }
];

const discountData = [
    {
        Id: '1d',
        col1: 'ABOB01BNID',
        col2: '11',
        col3: '1',
        col4: '2',
        col5: '',
        col6: '2',
        col7: '',
        col8: '',
        col9: '',
        col10: 'H001',
        col11: '25.09.2018',
        col12: 'XFCOLLINA',
        col13: '',
        col14: '',
        col15: '',
        col16: ''
    },
    {
        Id: '1d',
        col1: 'ABOB01BNIF',
        col2: '11',
        col3: '1',
        col4: '2',
        col5: '',
        col6: '2',
        col7: '',
        col8: '',
        col9: '',
        col10: 'H001',
        col11: '25.09.2018',
        col12: 'XFCOLLINA',
        col13: '',
        col14: '',
        col15: '',
        col16: ''  
    },
    {
        Id: '1d',
        col1: 'ABOB01STCA',
        col2: '11',
        col3: '1',
        col4: '2',
        col5: '',
        col6: '2',
        col7: '',
        col8: '',
        col9: '',
        col10: 'H001',
        col11: '25.09.2018',
        col12: 'XFCOLLINA',
        col13: '',
        col14: '',
        col15: '',
        col16: ''
    
    },
    {
        Id: '1d',
        col1: 'ABOB01STDF',
        col2: '11',
        col3: '1',
        col4: '2',
        col5: '',
        col6: '2',
        col7: '',
        col8: '',
        col9: '',
        col10: 'H001',
        col11: '25.09.2018',
        col12: 'XFCOLLINA',
        col13: '',
        col14: '',
        col15: '',
        col16: ''    
    },
    {
        Id: '1d',
        col1: 'ABOB01STDV',
        col2: '11',
        col3: '1',
        col4: '2',
        col5: '',
        col6: '2',
        col7: '',
        col8: '',
        col9: '',
        col10: 'H001',
        col11: '25.09.2018',
        col12: 'XFCOLLINA',
        col13: '',
        col14: '',
        col15: '',
        col16: ''    
    },
    {
        Id: '1d',
        col1: 'ABOB01STFF',
        col2: '11',
        col3: '1',
        col4: '2',
        col5: '',
        col6: '2',
        col7: '',
        col8: '',
        col9: '',
        col10: 'H001',
        col11: '25.09.2018',
        col12: 'XFCOLLINA',
        col13: '',
        col14: '',
        col15: '',
        col16: ''   
    },
    {
        Id: '1d',
        col1: 'ABOB01STFV',
        col2: '11',
        col3: '1',
        col4: '2',
        col5: '',
        col6: '2',
        col7: '',
        col8: '',
        col9: '',
        col10: 'H001',
        col11: '25.09.2018',
        col12: 'XFCOLLINA',
        col13: '',
        col14: '',
        col15: '',
        col16: ''    
    },
    {
        Id: '1d',
        col1: 'ABOB01STQF',
        col2: '11',
        col3: '1',
        col4: '2',
        col5: '',
        col6: '2',
        col7: '',
        col8: '',
        col9: '',
        col10: 'H001',
        col11: '25.09.2018',
        col12: 'XFCOLLINA',
        col13: '',
        col14: '',
        col15: '',
        col16: ''    
    },
    {
        Id: '1d',
        col1: 'ABOB01STQV',
        col2: '11',
        col3: '1',
        col4: '2',
        col5: '',
        col6: '2',
        col7: '',
        col8: '',
        col9: '',
        col10: 'H001',
        col11: '25.09.2018',
        col12: 'XFCOLLINA',
        col13: '',
        col14: '',
        col15: '',
        col16: ''    
    },
    {
        Id: '1d',
        col1: 'ABOB01SVAC',
        col2: '11',
        col3: '1',
        col4: '2',
        col5: '',
        col6: '2',
        col7: '',
        col8: '',
        col9: '',
        col10: 'H001',
        col11: '25.09.2018',
        col12: 'XFCOLLINA',
        col13: '',
        col14: '',
        col15: '',
        col16: ''    
    },
    {
        Id: '1d',
        col1: 'ABOB01SVAI',
        col2: '11',
        col3: '1',
        col4: '2',
        col5: '',
        col6: '2',
        col7: '',
        col8: '',
        col9: '',
        col10: 'H001',
        col11: '25.09.2018',
        col12: 'XFCOLLINA',
        col13: '',
        col14: '',
        col15: '',
        col16: ''    
    },
    {
        Id: '1d',
        col1: 'ABOB02SVAC',
        col2: '11',
        col3: '1',
        col4: '2',
        col5: '',
        col6: '2',
        col7: '',
        col8: '',
        col9: '',
        col10: 'H001',
        col11: '25.09.2018',
        col12: 'XFCOLLINA',
        col13: '',
        col14: '',
        col15: '',
        col16: ''
    }
];

const valueData = [
    {
        Id: '1c',
        col1: 'value 1',
        col2: '02'
    },
    {
        Id: '2c',
        col1: 'value2',
        col2: '02'
    }
];

const stringData = [
    {
        Id: '1c',
        col1: 'string 1',
        col2: '02'
    },
    {
        Id: '2c',
        col1: 'string 2',
        col2: '02'
    }
];