/**
 * @author Marco Arci (marco.arci@webresults.it)
 * @date 23/07/2021
 * @description HDT_LC_ActivityDetailTst - Classe di Test
 * @history Inserire Nome Cognome – Data Modifica – Descrizione della modifica
 */
@isTest
public with sharing class HDT_LC_ActivityDetailTst {

    @isTest public static void getActivityById(){

    }

    @isTest public static void getActivityTemplateById(){

    }

    @isTest public static void getFieldsTemplateById(){

    }

    @isTest public static void getDynamicSectionByFieldsTemplateId(){

    }

    @isTest public static void getDynamicFieldsByDynamicSectionId(){

    }
}
