@isTest
public with sharing class HDT_TRH_SelfReadingEventTst {
    
    //DEBUG
    
    
    //DATA
    
    
    //TEST SETUP
    
    
    
    //TESTS
    
    //COVERAGE INCREASE TEST
    @isTest
    private static void coverageIncreaseTest() {
        
        //SETUP
        
        
        //TESTING
        
        
        //RETRIEVING DATA
        
        
        //ASSERTS
        
        
    }
}
