@isTest
public with sharing class HDT_SRV_ReminderBlockTst {
    
    //DEBUG
    public static final String TEST_NAME = 'HDT_LC_AccountAlertsTst';
    
    
    //DATA
    //private static HDT_UTL_Constants constants = new HDT_UTL_Constants();
    
    
    
    
    //TEST SETUP
    
    
    
    //TESTS
    
    @isTest
    private static void createRequestBodyTest() {
        //MOCK
    }
    
}
