/*

{
  "phoneNumber" : "3287777777",
  "fiscalCode" : "BRRSMN81T22I459C",
  "clientTypology" : "Domestico",
  "contactName" : "Simone tortora",
  "streetCode" : "041044811157",
  "city" : "PESARO",
  "street" : "VIALE VENTIQUATTRO MAGGIO",
  "streetNumber" : "16",
  "typeInt" : "Ingombr+RAEE_NOAPP-IURD0033",
  "requestCode" : "11111",
  "materialDescription" : "Prodotto 1: Valigia varie tipologie"
}


*/
@isTest
public with sharing class HDT_WS_GarbageManTest {
    
}
